import {
  FamilyMember,
  BudgetCategory,
  Transaction,
  BalanceSettlement,
  ScheduledBill,
  AlertTrigger
} from './types';

export const INITIAL_MEMBERS: FamilyMember[] = [
  {
    id: 'sarah',
    name: 'Sarah Miller',
    alias: 'Mom',
    role: 'admin',
    roleTag: 'Parent / Admin',
    roleDescription: 'Primary Organizer',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAS1rIBSI5zryInlqvs9Q8_KbNclRx0yixQcH6ALlUbnF_av1GbCNQF5e-Ox-KRS-yZcE7Y23BTBz32FnrQUONZLChFN4LDG9YEcO_1Av670yXaFyLOEWGsNspRVMxScT33W3A8tX2lD0JfE_Dlg3f2VdgjmzB3bmE3yDAP9x8tVDsUr6KnjaX-T7oc-my5DRHdxZCUwwop-RoDmsSyhSlGmvjtuYOxiZn-Xyl6jHtX3Z9eHGnMpy2e',
    avatarInitial: 'SM',
    monthlySpend: 2140.00,
    budgetCap: 3150.00,
    available: 1010.00,
    transactionsCount: 14,
    percentageUsed: 68,
    cardName: 'Chase Sapphire',
    cardLast4: '4821',
    cardType: 'Credit',
    cardStatus: 'Active',
    topCategories: [
      { name: 'Groceries', icon: 'local_grocery_store', amount: 1280 },
      { name: 'Health', icon: 'health_and_safety', amount: 250 },
      { name: 'Kids', icon: 'child_care', amount: 610 },
    ],
  },
  {
    id: 'mark',
    name: 'Mark Miller',
    alias: 'Dad',
    role: 'admin',
    roleTag: 'Parent / Admin',
    roleDescription: 'Co-Admin',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB6X9yHOj3bJ5QiOtjdRTRN97a3QwFiyqiuDaZhKCy7c0aDauc6ppSJUkvA2BSldfhmPTG97K7_mK4kxIBcXv5Pwbs3NPcmuhBtm87o20VBrt6spz3JoPCtzsl4R6HMxNfpfKI02cHTF-61qi9YyPDBL8LdM_4x6ccgvU2z5Nklg7tWmzmcLfgc981ok9my2X0mZ1GHW4iprco6MDSlqMuBxLi_QUslgfMpp4kO05LKfJeSTEAlcqEc',
    avatarInitial: 'MM',
    monthlySpend: 1620.00,
    budgetCap: 2200.00,
    available: 580.00,
    transactionsCount: 9,
    percentageUsed: 74,
    cardName: 'Amex Blue',
    cardLast4: '9012',
    cardType: 'Credit',
    cardStatus: 'Active',
    topCategories: [
      { name: 'Housing', icon: 'roofing', amount: 1200 },
      { name: 'Transport', icon: 'commute', amount: 290 },
      { name: 'Utilities', icon: 'bolt', amount: 130 },
    ],
  },
  {
    id: 'alex',
    name: 'Alex Miller',
    alias: 'Teen',
    role: 'dependent',
    roleTag: 'Dependent / Teen',
    roleDescription: 'Greenlight Debit',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCs01EbZDxUJ6aCiPOHKzWhCPJZh9BWTc84HH1LcPkCYk2RZ6YkB5ZKhZFKezWl3Zb2vAmBNK0VFImRRJd06xTmsxVKWnq4z1g21ct7p3Mczxc67AMBcrHLa56Oq-VlNJCxmZH78hg6HZ8fWtlPEbgF0uVi5Gr45fvH5sQWARdOFr6Utt3No-kW22yzZcvd2BfGDOm_F4Z_kQEHClMMQdPKMpLgmDtBVLpxVV4XorQteBaTbeN3hU_x',
    avatarInitial: 'AM',
    monthlySpend: 185.00,
    budgetCap: 200.00,
    available: 15.00,
    transactionsCount: 6,
    percentageUsed: 85,
    cardName: 'Greenlight Teen Card',
    cardLast4: '3341',
    cardType: 'Debit',
    cardStatus: 'Active',
    isTeen: true,
    age: 15,
    allowancePeriod: '/mo',
    refreshesInDays: 6,
    safetyVelocity: '$25/day safety velocity',
    dailyCap: 25.00,
    topCategories: [
      { name: 'School Lunch', icon: 'lunch_dining', amount: 95 },
      { name: 'Books & Supplies', icon: 'menu_book', amount: 65 },
      { name: 'Transit', icon: 'directions_bus', amount: 25 },
    ],
  },
  {
    id: 'maya',
    name: 'Maya Miller',
    alias: 'College',
    role: 'dependent',
    roleTag: 'Dependent / College',
    roleDescription: 'Campus Living',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCyru3TuqJ4-gpNLwamd4pAH-VOfqv-ysxJ7YT30oPyrXCjCtc-15_rNlw3pa_HIGEROPHHkuQ_SwVs7VIXMsW-lYzUBiRxNsGCM1yKb4qc04p5H9nz_7VQkMYHg1RJZl32_pOOajVlVQw5EhjxBzZLVjr1dagVV53Iy4s9McptLHfJaKRP50TAATIwlef-I-oDcm_-CZ1KTX21V7JiGxJwaHKflG6-vEmWIFaVKiKm8ArP8f9mt3Dp',
    avatarInitial: 'MY',
    monthlySpend: 340.50,
    budgetCap: 400.00,
    available: 59.50,
    transactionsCount: 11,
    percentageUsed: 85,
    cardName: 'Discover Student',
    cardLast4: '7714',
    cardType: 'Credit',
    cardStatus: 'Active',
    isStudent: true,
    age: 20,
    allowancePeriod: '/mo',
    hasReimbursementRequest: true,
    reimbursementDetails: {
      id: 'req_chem_book',
      amount: 45.00,
      purpose: 'Chemistry Textbook (Pending Approval)',
      status: 'pending',
    },
    topCategories: [
      { name: 'Dorm Supplies', icon: 'home', amount: 180 },
      { name: 'Campus Dining', icon: 'restaurant', amount: 115 },
      { name: 'Study & Print', icon: 'school', amount: 45.50 },
    ],
  },
];

export const INITIAL_CATEGORIES: BudgetCategory[] = [
  {
    id: 'housing',
    name: 'Housing & Rent',
    icon: 'home',
    spent: 1800.00,
    limit: 1800.00,
    subtext: 'Fixed Contract · Mortgage & HOA',
    percentage: 100,
    status: 'normal',
    isLocked: true,
    alertActive: true,
    septemberSpent: 1800.00,
    octoberSpent: 1800.00,
    variancePercentage: 0,
    varianceDirection: 'down',
  },
  {
    id: 'groceries',
    name: 'Groceries & Household',
    icon: 'shopping_cart',
    spent: 1280.00,
    limit: 1500.00,
    subtext: "Costco, Trader Joe's, Target",
    percentage: 85.3,
    status: 'caution',
    alertActive: true,
    septemberSpent: 1180.00,
    octoberSpent: 1120.00,
    variancePercentage: -5.1,
    varianceDirection: 'down',
  },
  {
    id: 'dining',
    name: 'Dining Out & Takeout',
    icon: 'restaurant',
    spent: 410.00,
    limit: 350.00,
    subtext: 'Exceeded monthly threshold',
    percentage: 117.1,
    status: 'critical',
    alertActive: true,
    septemberSpent: 462.00,
    octoberSpent: 620.00,
    variancePercentage: 34.2,
    varianceDirection: 'up',
  },
  {
    id: 'allowances',
    name: 'Personal Allowances',
    icon: 'account_balance_wallet',
    spent: 650.00,
    limit: 700.00,
    subtext: 'Sarah ($350) · Mark ($300)',
    percentage: 92.8,
    status: 'caution',
    alertActive: true,
    septemberSpent: 650.00,
    octoberSpent: 650.00,
    variancePercentage: 0,
    varianceDirection: 'down',
  },
  {
    id: 'utilities',
    name: 'Utilities & Internet',
    icon: 'bolt',
    spent: 345.00,
    limit: 450.00,
    subtext: 'ConEd, Verizon Fios, Water',
    percentage: 76.6,
    status: 'normal',
    alertActive: true,
    septemberSpent: 480.00,
    octoberSpent: 410.00,
    variancePercentage: -14.6,
    varianceDirection: 'down',
  },
  {
    id: 'kids',
    name: 'Kids, Education & Sports',
    icon: 'school',
    spent: 420.00,
    limit: 600.00,
    subtext: 'Soccer club, Piano lessons, Books',
    percentage: 70.0,
    status: 'normal',
    alertActive: true,
    septemberSpent: 580.00,
    octoberSpent: 490.00,
    variancePercentage: -15.5,
    varianceDirection: 'down',
  },
  {
    id: 'transport',
    name: 'Transportation & Fuel',
    icon: 'directions_car',
    spent: 280.00,
    limit: 400.00,
    subtext: 'Shell Gas, Subway transit pass',
    percentage: 70.0,
    status: 'normal',
    alertActive: true,
    septemberSpent: 390.00,
    octoberSpent: 385.00,
    variancePercentage: -1.2,
    varianceDirection: 'down',
  },
  {
    id: 'health',
    name: 'Healthcare & Pharmacy',
    icon: 'medical_services',
    spent: 150.00,
    limit: 300.00,
    subtext: 'CVS Caremark, Copays',
    percentage: 50.0,
    status: 'normal',
    alertActive: true,
    septemberSpent: 160.00,
    octoberSpent: 150.00,
    variancePercentage: -6.2,
    varianceDirection: 'down',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_1',
    date: 'Oct 28, 2024',
    time: '2:45 PM',
    merchant: "Trader Joe's #142",
    description: 'Weekly family essentials & snacks',
    paidBy: 'Sarah Miller',
    paidById: 'sarah',
    category: 'Groceries',
    categoryIcon: 'shopping_cart',
    splitStatus: 'Shared 100%',
    splitType: 'joint_50_50',
    amount: 184.22,
    hasReceipt: true,
    taxFlag: false,
    paymentMethod: 'Chase Sapphire ••8912',
    badgeBg: 'bg-emerald-50',
    badgeText: 'text-emerald-700',
  },
  {
    id: 'tx_2',
    date: 'Oct 26, 2024',
    time: '8:15 PM',
    merchant: "L'Osteria Family Dinner",
    description: "Maya's soccer tournament celebration",
    paidBy: 'Mark Miller',
    paidById: 'mark',
    category: 'Dining Out',
    categoryIcon: 'restaurant',
    splitStatus: 'Full Family Pool',
    splitType: 'full_pool',
    amount: 142.50,
    hasReceipt: true,
    taxFlag: false,
    paymentMethod: 'Amex Gold ••4001',
    badgeBg: 'bg-rose-50',
    badgeText: 'text-rose-700',
  },
  {
    id: 'tx_3',
    date: 'Oct 24, 2024',
    time: '11:30 AM',
    merchant: 'University Bookstore (Alex)',
    description: 'Chemistry lab textbooks & portal access',
    paidBy: 'Alex Miller',
    paidById: 'alex',
    category: 'Education',
    categoryIcon: 'school',
    splitStatus: 'College 529 Account',
    splitType: 'allowance',
    amount: 218.40,
    hasReceipt: true,
    taxFlag: true,
    paymentMethod: 'KinDebit Alex ••3119',
    badgeBg: 'bg-blue-50',
    badgeText: 'text-blue-700',
  },
  {
    id: 'tx_4',
    date: 'Oct 20, 2024',
    time: '9:15 AM',
    merchant: 'CleanPower Electric & Gas',
    description: 'Monthly auto-debit utility billing',
    paidBy: 'Sarah Miller',
    paidById: 'sarah',
    category: 'Utilities',
    categoryIcon: 'bolt',
    splitStatus: 'Joint (50/50)',
    splitType: 'joint_50_50',
    amount: 182.35,
    hasReceipt: true,
    taxFlag: false,
    paymentMethod: 'Joint ACH ••7701',
    badgeBg: 'bg-amber-50',
    badgeText: 'text-amber-700',
  },
  {
    id: 'tx_5',
    date: 'Oct 18, 2024',
    time: '4:20 PM',
    merchant: 'Blick Art Materials',
    description: 'Maya AP Studio art supplies',
    paidBy: 'Maya Miller',
    paidById: 'maya',
    category: 'School / Art',
    categoryIcon: 'palette',
    splitStatus: 'Allowance Cap',
    splitType: 'allowance',
    amount: 64.10,
    hasReceipt: true,
    taxFlag: false,
    paymentMethod: 'Maya Pre-Paid ••1022',
    badgeBg: 'bg-indigo-50',
    badgeText: 'text-indigo-700',
  },
  {
    id: 'tx_6',
    date: 'Oct 16, 2024',
    time: '8:05 AM',
    merchant: 'Shell Gas Station',
    description: 'Family SUV Tank Fill',
    paidBy: 'Mark Miller',
    paidById: 'mark',
    category: 'Transport',
    categoryIcon: 'directions_car',
    splitStatus: 'Shared 100%',
    splitType: 'joint_50_50',
    amount: 56.80,
    hasReceipt: true,
    taxFlag: false,
    paymentMethod: 'Amex Blue ••9012',
    badgeBg: 'bg-sky-50',
    badgeText: 'text-sky-700',
  },
  {
    id: 'tx_7',
    date: 'Oct 15, 2024',
    time: '6:30 PM',
    merchant: 'Carpool Reimbursement (Soccer Club)',
    description: 'Direct deposit from Davis family',
    paidBy: 'Sarah Miller',
    paidById: 'sarah',
    category: 'Income',
    categoryIcon: 'payments',
    splitStatus: 'Joint Credit',
    splitType: 'income',
    amount: 35.00,
    isIncome: true,
    hasReceipt: false,
    taxFlag: false,
    paymentMethod: 'Joint Credit',
    badgeBg: 'bg-emerald-50',
    badgeText: 'text-emerald-700',
  },
];

export const INITIAL_SETTLEMENTS: BalanceSettlement[] = [
  {
    id: 'set_1',
    title: 'Shared Family Dinner at Olive Bistro',
    category: 'Dining',
    date: 'Yesterday, 7:45 PM',
    description: 'Mark paid $120.00 for shared family dinner → Sarah owes Mark $60.00',
    payerName: 'Sarah Miller',
    payerInitial: 'M',
    payerBg: 'bg-[#EEF2FF]',
    payerText: 'text-[#4F46E5]',
    recipientName: 'Mark Miller',
    amount: 60.00,
    status: 'pending',
    methodNote: 'Pending settlement',
  },
  {
    id: 'set_2',
    title: "Maya's Semester Transit Pass",
    category: 'Transit',
    date: 'Sep 22, 2:15 PM',
    description: "Sarah covered Maya's semester transit pass $75.00 → Reimbursed automatically from student pool",
    payerName: 'Sarah Miller',
    payerInitial: 'S',
    payerBg: 'bg-[#ECFDF5]',
    payerText: 'text-[#047857]',
    recipientName: 'Student Pool',
    amount: 75.00,
    status: 'settled',
    methodNote: 'Reconciled automatically',
  },
  {
    id: 'set_3',
    title: 'Costco Household Restock',
    category: 'Groceries',
    date: 'Sep 18, 11:30 AM',
    description: 'Sarah paid $340.00 → Split 50/50 with Mark ($170.00)',
    payerName: 'Mark Miller',
    payerInitial: 'M',
    payerBg: 'bg-slate-100',
    payerText: 'text-slate-600',
    recipientName: 'Sarah Miller',
    amount: 170.00,
    status: 'archived',
    methodNote: 'Settled via Chase QuickPay',
  },
];

export const INITIAL_BILLS: ScheduledBill[] = [
  {
    id: 'bill_1',
    day: 22,
    dueDate: 'Oct 22, 2024',
    title: 'ConEdison Power',
    assignedPayer: 'Mark M.',
    amount: 185.00,
    statusNote: 'Verified Buffer',
    isAutoPay: true,
  },
  {
    id: 'bill_2',
    day: 25,
    dueDate: 'Oct 25, 2024',
    title: 'Verizon Fios Gigabit',
    assignedPayer: 'Sarah M.',
    amount: 89.99,
    statusNote: 'Scheduled',
    isAutoPay: true,
  },
  {
    id: 'bill_3',
    day: 28,
    dueDate: 'Oct 28, 2024',
    title: 'State Farm Auto Ins.',
    assignedPayer: 'Mark M.',
    amount: 142.20,
    statusNote: 'Manual Check',
    isAutoPay: false,
  },
];

export const INITIAL_ALERTS: AlertTrigger[] = [
  {
    id: 'alert_1',
    type: 'warning',
    title: 'Groceries Budget at 86%',
    category: 'Groceries',
    triggeredTime: 'Triggered 2h ago',
    description: '$1,280 spent of $1,500 limit.',
    details: 'Projected to exceed limit by $140 before Oct 31 based on recent 4-day frequency.',
    actionPrimaryText: 'Increase Cap',
    actionSecondaryText: 'Set Daily Cap',
  },
  {
    id: 'alert_2',
    type: 'critical',
    title: 'Dining Out Exceeded by $60.00',
    category: 'Dining Out',
    triggeredTime: 'Oct 14',
    description: '$410.00 spent vs $350.00 cap (117.1%).',
    details: 'Triggered by transaction: Cheesecake Factory ($115.00 on Oct 14) by Sarah.',
    actionPrimaryText: 'Lock Card',
    actionSecondaryText: 'Reallocate Funds',
  },
  {
    id: 'alert_3',
    type: 'scheduled',
    title: 'ConEdison Electric & Gas',
    category: 'Utilities',
    triggeredTime: 'Due in 3 days (Oct 22)',
    description: 'Estimated $185.00 auto-pay scheduled from Miller Joint Checking.',
    details: 'Sufficient buffer verified in Utilities category.',
    actionPrimaryText: 'Auto-Pay Active',
    actionSecondaryText: 'View Bill PDF',
  },
];
